
theme: jekyll-theme-hacker
name: Ayush Zenith
description: Hi! I'm Ayush Zenith. A high school sophomore from Andover High School, Andover, Massachusetts and this page is about an application I built with the help of a friend, Samar Seth.
