theme: jekyll-theme-midnight
name: Ayush Zenith
description: Hi! I'm Ayush Zenith. A high school sophomore from Andover High School, Andover, Massachusetts and this page is about an application I built with the help of a friend, Samar Seth, who is a junior at Philips Academy, Andover, Massachusetts.
avatar: https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwigz8z5ws3cAhWOxVkKHVk-BYsQjRx6BAgBEAU&url=https%3A%2F%2Fwww.finecooking.com%2Frecipe%2Fpineapple-strawberry-and-lychee-parfaits&psig=AOvVaw2SBimlOSouwHOpQuCdMxaY&ust=1533270253066491
